config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'main#home'

  get 'about', to: 'main#about'

  get 'grammar', to: 'main#grammar'
  get 'sentence_structure', to: 'main#sentence_structure'
  get 'vocabulary_building', to: 'main#vocabulary_building'
  get 'essay_writing', to: 'main#essay_writing'
  get 'story_writing', to: 'main#story_writing'
  get 'rhetorical_devices', to: 'main#rhetorical_devices'
  get 'classic_english', to: 'main#classic_english'

  resources :users, only: [:index, :show, :edit, :update, :destroy]

  patch 'users/:id/update', to: 'users#reactivate_user', as: 'reactivate_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:student, :guardian, :teacher, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :student
  end

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  paginates_per 5

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

# provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def gravatar
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @current_page = 'homepage'
  end

  def about
    @current_page = 'aboutpage'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # Soft DELETE resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  private
    def sign_up_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :authorize_admin

  def index
    @users_count = User.count
    @users_by_roles = User.group(:role).order(:role).count
    @deleted_users_count = User.where.not(deleted_at: nil).count

    if params[:term] && !params[:term].empty?
      @users = User.where("name like :search or email like :search", search: "%#{params[:term]}%").order(id: :desc).page(params[:page])
    else
      if params[:deleted_at]
        @users = User.where.not(deleted_at: nil).order(id: :desc).page(params[:page])
      else
        if params[:role] && !params[:role].empty?
          @users = User.where(role: params[:role]).order(id: :desc).page(params[:page])
        else
          @users = User.order(id: :desc).page(params[:page])
        end
      end
    end

end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "User updated successfully."
     redirect_to @user
   else
     render 'edit'
   end
  end

  def destroy
   @user = User.find(params[:id])
   if @user.destroy
     redirect_to users_url, notice: "User deleted."
   end
  end

  def reactivate_user
      @user = User.find(params[:id])
      if @user.update_attribute(:deleted_at, nil)
        flash[:success] = "User reactivated successfully."
        redirect_to @user
      else
        render 'edit'
      end
    end


  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :role)
    end

    def authorize_admin
      if current_user.role.nil? || current_user.role.to_sym != :admin
        flash[:alert] = "Not Authorized!"
        redirect_to root_url
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!

    return "" unless devise_error_messages?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML

    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>

    HTML
    html.html_safe

  end
  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="row-fluid">
        <%= "Smashin English Academy"%>
        <% if user_signed_in? %>
          Signed in as <strong><%= current_user.email %></strong>
            <% if current_user.try(:admin?) %>
                Account Type: <strong>Admin</strong>
            <% else %>
                Account Type: <strong><%= current_user.role %></strong>
            <% end %>
        <% else %>
          Not Signed in
        <% end %>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <!--<img src="/assets/Logo-1.jpg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    <%= image_tag "Smashin-Logo-3.jpg", width: 70, height: 40, class: "d-inline-block align-top", alt: "" %>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>

      <li>
        <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  User
              </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete', class: 'nav-link' %>
                  <%= link_to 'Edit User Profile', edit_user_registration_path, class: 'nav-link' %>
              </div>
            </li>

            <% if current_user.role && current_user.role.to_sym == :admin %>
              <li class="nav-item">
                <%= link_to 'Users', users_path, class: 'nav-link' %>
              </li>
            <% end %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Subjects
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Grammar', grammar_path, class: 'dropdown-item' %>
                <%= link_to 'Sentence Structure', sentence_structure_path, class: 'dropdown-item' %>
                <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'dropdown-item' %>
                <%= link_to 'Essay Writing', essay_writing_path, class: 'dropdown-item' %>
                <%= link_to 'Story Writing', story_writing_path, class: 'dropdown-item' %>
                <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'dropdown-item' %>
                <%= link_to 'Classic English', classic_english_path, class: 'dropdown-item' %>

              </div>
            </li>

            <li>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'  %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </li>

    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if current_user %>
          <div class="media-right">
            <%= image_tag current_user.gravatar, class: "media-objectt", style: "height:40px; width:40px;" %>
          </div>
        <% end %>
      </li>
    </ul>

  </div>
</nav>

app/views/main/about.html.erb
<div class="special-container">
  <%= image_tag "Background-2.jpg", width: "100%", height: "100%", class: "d-inline-block align-top", alt: "About" %>

  <div class="centered-top-lower">
    <h1 style="color: orange; font-family: SCRIPTIN;font-size: 200px;">
      About
    </h1>
  </div>

</div>

<div class="container-fluid">
  <h2 style="color: black; font-family: Architex; font-size: 40px; font-weight: bold;">
    Sandra Mashin is a psychologist and teacher who has worked in the education field for over twenty years.
    She has spent decades researching her passion - students learning a collection of effective writing skills.
    Through her research she has devised a unique and easy to understand writing program that aims at teaching students how to properly structure sentences, incorporate vocabulary/rhetoric and formulate effective essays and stories.
    In addition, her time spent working as a principal, department head and tutor provided her with a wealth of insight into the individualized needs of students and parents.
    As a teacher, Sandra specializes in teaching a range of exceptional students, ranging from gifted to students with learning disabilities.
    Her mission is to provide the language skills that are no longer taught so that students can build successful careers of their dream.
    Her program is for everyone.
  </h2>
</div>

app/views/main/classic_english.html.erb
<h1>Classic English</h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item active' %>
  </h4>
</nav>

<div class="row">

  <div class="col-lg-6">
    <%= image_tag "laurenz-kleinheider-633724-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
  </div>

  <div class="col-lg-6">
    <h1> Content... <h1>
  </div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/main/grammar.html.erb
<h1>Grammar</h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item active' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item' %>
  </h4>
</nav>

<div class="row">

  <div class="col-lg-6">
    <%= image_tag "michael-d-beckwith-575798-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
  </div>

  <div class="col-lg-6">
    <h1> Content... <h1>
  </div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/main/home.html.erb
<div class="special-container">
  <%= image_tag "Smashin-2.jpg", width: "100%", height: "100%", class: "d-inline-block align-top", alt: "Home" %>

  <div class="centered-top">
  </br></br>
    <h1 style="color: black; font-family: SCRIPTIN; font-size: 85px; font-weight: bold;">
      Smashin English
    </h1>
  </div>

  </br></br>

  <div class=row-fluid>
    <h3 style="color: black; font-family: SCRIPTIN;font-size: 60px;">
          More Words! Bigger Words! Better Words!
    </h3>
  </div>

</div>

<div class="row-fluid">
  </br></br>
</div>

<div class="row">
  <div class="col-lg-6">
    <div style="text-align: center;">
      <div style="display: inline-block; text-align: left;">

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "michael-d-beckwith-575798-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Grammar', grammar_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "eugenio-mazzone-190204-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Sentence Structure', sentence_structure_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "zoran-zonde-stojanovski-44795-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Vocabulary Building', vocabulary_building_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "rawpixel-586682-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Essay Writing', essay_writing_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

      </div>
    </div>
  </div>

  <div class="col-lg-6">
    <div style="text-align: center;">
      <div style="display: inline-block; text-align: left;">

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "mark-rasmuson-108148-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Story Writing', story_writing_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "vladimir-proskurovskiy-638465-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td width="100" class="middle">
            <div class="media">
              <div class="media-left">
                  <%= image_tag "laurenz-kleinheider-633724-unsplash-min.jpg", class: "media thumbnail img", style: 'height:100px;width:80px;' %>
              </div>
              <div class="media-body">
                  <h1 class="media-heading"><%=link_to 'Classic English', classic_english_path, class: 'nav-link'  %></h1>
              </div>
            </div>
          </td>
        </tr>

      </div>
    </div>
  </div>

</div>

app/views/main/rhetorical_devices.html.erb
<h1>Rhetorical Devices</h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item active' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item' %>
  </h4>
</nav>

<div class="row">

  <div class="col-lg-6">
    <%= image_tag "vladimir-proskurovskiy-638465-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
  </div>

  <div class="col-lg-6">
    <h1> Content... <h1>
  </div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/main/sentence_structure.html.erb
<h1> Sentence Structure </h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item active' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item' %>
  </h4>
</nav>

<div class="row">

  <div class="col-lg-6">
    <%= image_tag "eugenio-mazzone-190204-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
  </div>

  <div class="col-lg-6">
    <h1> Content... <h1>
  </div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/main/story_writing.html.erb
<h1>Story Writing</h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item active' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item' %>
  </h4>
</nav>

<div class="col-lg-6">
  <%= image_tag "mark-rasmuson-108148-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
</div>

<div class="col-lg-6">
  <h1> Content... <h1>
</div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/main/vocabulary_building.html.erb
<h1>Vocabulary Building</h1>

<nav class="breadcrumb row">
  <h4>
    <%= link_to 'Grammar', grammar_path, class: 'breadcrumb-item' %>
    <%= link_to 'Sentence Structure', sentence_structure_path, class: 'breadcrumb-item' %>
    <%= link_to 'Vocabulary Building', vocabulary_building_path, class: 'breadcrumb-item active' %>
    <%= link_to 'Essay Writing', essay_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Story Writing', story_writing_path, class: 'breadcrumb-item' %>
    <%= link_to 'Rhetorical Devices', rhetorical_devices_path, class: 'breadcrumb-item' %>
    <%= link_to 'Classic English', classic_english_path, class: 'breadcrumb-item' %>
  </h4>
</nav>

<div class="row">

  <div class="col-lg-6">
    <%= image_tag "zoran-zonde-stojanovski-44795-unsplash-min.jpg", class: "media thumbnail img", style: 'height:500px; width:500px; padding:1px;' %>
  </div>

  <div class="col-lg-6">
    <h1> Content... <h1>
  </div>

</div>

</br></br>

<div class="row-fluid">
  <h2>More Content... </h2>
</div>

app/views/users/_user.html.erb
<tr>
  <td width="100" class="middle">
    <div class="media">
      <div class="media-left">
          <%= image_tag user.gravatar, class: "media-object" %>
          <h6 class="text-center">ID: <%= user.id %></h6>
      </div>

      <div class="media-body">
        <% if user.deleted_at %>
          <del><h4 class="media-heading"><%= user.name %></h4></del>
        <% else %>
          <h4 class="media-heading"><%= user.name %></h4>
        <% end %>

        <div class="row">
          <div class="col-6">
            Email: <strong><%= user.email %></strong>
          </div>
          <div class="col-6">
            Role: <strong><%= user.role %></strong>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            Created At: <strong><%= user.created_at %></strong>
          </div>
          <div class="col-6">
            Updated At: <strong><%= user.updated_at %></strong>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            Confirmed At: <strong><%= user.confirmed_at %></strong>
          </div>
          <div class="col-6">
            Last Signed In At: <strong><%= user.last_sign_in_at %></strong>
          </div>
        </div>

      </div>
    </div>
  </td>

  <td width="100" class="middle">
    <div class="media float-right">
      <div class="media-right">
        <%= link_to '<i class="fa fa-info" style="font-size:18px;color:white;"></i>'.html_safe, user, method: "get", class: "btn btn-circle btn-success btn-xs" %>
        <%= link_to '<i class="fa fa-pencil-square-o" style="font-size:18px;color:white"></i>'.html_safe, edit_user_path(user), method: "get", class: "btn btn-circle btn-info btn-xs" %>
        <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'show' %>

<div class="container-fluid">
  <%= simple_form_for(@user) do |f| %>
    <div class="form-inputs">
      <%= f.label :role, required: true, label: "User role:" %>
      <%= f.select(:role, [['Student', 'student'], ['Guardian', 'guardian'], ['Teacher', 'teacher'], ['Admin', 'admin']]) %><br />
    </div>

    <br />

    <div class="form-actions">
      <%= f.button :submit, "Update", class: "btn-primary" %>
    </div>

  <% end %>
</div>

<br />

<div class="row-fluid">
  <%= link_to '<i class="fa fa-info" style="font-size:18px;color:white;"></i>'.html_safe, @user, method: "get", class: "btn btn-circle btn-success btn-xs" %>
  <%= link_to '<i class="fa fa-list" style="font-size:18px;color:white;"></i>'.html_safe, users_path, method: "get", class: "btn btn-circle btn-success btn-xs" %>
  <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, @user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% if @user.deleted_at %>
    <p>Reactivate User? <%= link_to "Reactivate", reactivate_user_path(@user),  method: "patch", class: "btn-outline-danger" %></p>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>
  Users
  <%= form_tag(users_path, class: "form-inline my-2 my-lg-0", role: "search", method: :get) do %>
    <div class="input-group">
      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search...", autocomplete: "off" %>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </div>
  <% end %>
</h1>

<div class="row-fluid">
  <div class="row">

    <div class="col-2">

      <table class="table table-striped table-hover">

        <tbody>

          <tr>
            <% active = (params[:role] == nil || params[:role].empty?) && !params[:deleted_at] ? 'active' : '' %>
            <%= link_to users_path, class: "list-group-item #{active}" do %>
              All Users <span class="badge badge-light float-right"><%= @users_count %></span>
            <% end %>
          </tr>

          <% @users_by_roles.each do |role, count| %>
            <tr>
              <% active = params[:role] == role ? 'active' : '' %>
              <%= link_to users_path(role: role), class: "list-group-item #{active}" do %>
                <%= role.nil? ? "None " : role.to_s.capitalize + "s " %><span class="badge badge-light float-right"><%= count %></span>
              <% end %>
            </tr>
          <% end %>

          <tr>
            <% active = params[:deleted_at] ? 'active' : '' %>
            <%= link_to users_path(deleted_at: !nil), class: "list-group-item #{active}" do %>
              Deleted <span class="badge badge-light float-right"><%= @deleted_users_count %></span>
            <% end %>
          </tr>

        </tbody>

      </table>

    </div>

    <div class="col-10">

      <% if @users.blank? %>
        <div class="alert alert-warning">
          <strong>Records not found</strong>
        </div>
      <% end %>

      <div class="text-center">
        <%= paginate @users %>
      </div>

      <div class="panel panel-default">
        <table class="table">
          <%= render @users %>
        </table>
      </div>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<h1>Show User <%= @user.name %></h1>

<%= render 'show' %>

<div>
 <%= link_to '<i class="fa fa-list" style="font-size:18px;color:white;"></i>'.html_safe, users_path, method: "get", class: "btn btn-circle btn-success btn-xs" %>
 <%= link_to '<i class="fa fa-pencil-square-o" style="font-size:18px;color:white"></i>'.html_safe, edit_user_path(@user), method: "get", class: "btn btn-circle btn-info btn-xs" %>
 <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, @user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>